require:
  - rubocop-performance
  - rubocop-rspec
  - rubocop-rails

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'log/**/*'
    - 'storage/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Layout/HashAlignment:
  Exclude:
    - 'lib/tasks/auto_annotate_models.rake'

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
