default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  database: <%= ENV['DATABASE_NAME'] || 'minustah' %>

test:
  <<: *default
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USERNAME'] || 'postgres' %>
  password: <%= ENV['DATABASE_PASSWORD'] || 'postgres' %>
  database: <%= ENV['DATABASE_NAME'] || 'minustah_test' %>

production:
  <<: *default
  url:  <%= ENV["DATABASE_URL"] %>
